name: prisma-extension-soft-delete
on:
  push:
    branches:
      - 'main'
      - 'next'
  pull_request:

permissions:
  contents: write # Required to push to the repository
  issues: write # Required to create issues
  pull-requests: write # Required to create pull requests
  id-token: write # Required to create id tokens
  packages: write # Required to publish packages

jobs:
  test:
    name: 'node ${{ matrix.node }} chrome ${{ matrix.os }} '
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aquafoxjsc'
      
      - name: Setup npm authentication for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@aquafoxjsc:registry=https://npm.pkg.github.com" >> ~/.npmrc
      
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: npm run validate
        env:
          CI: true
  release:
    runs-on: ubuntu-latest
    # needs: test  # Skip tests for now
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@aquafoxjsc'
      
      - name: Setup npm authentication for GitHub Packages
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" > ~/.npmrc
          echo "@aquafoxjsc:registry=https://npm.pkg.github.com" >> ~/.npmrc
      
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - run: npm run build
      - run: ls -asl dist
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
